trigger:
  batch: true
  paths:
    include:
      - nginx/**
      - pipelines/nginx.yaml

variables:
  - group: nginx

pool: agent

jobs:
  - job: nginx
    steps:
      - bash: |
          #!/bin/bash
          set -e
          sudo apt-get update -y
          sudo apt-get install nginx -y
          sudo systemctl enable nginx --now
        displayName: Install Nginx
      - checkout: self
        clean: true
      - bash: |
          #!/bin/bash
          set -e
          sudo mkdir -p /var/www/html/{prd,dev,uat}
          mkdir -p /etc/ssl/certs/
          chown -R www-data: /var/www/html/
        displayName: setup folders for frontend
        workingDirectory: nginx
      - bash: |
          #!/bin/bash
          cp sundarammutual.crt /etc/ssl/certs/
          echo $(PRIVATE_KEY) | base64 --decode > /etc/ssl/private/sundarammutual.key
          chown -R www-data: /etc/ssl/certs/
        workingDirectory: nginx
        displayName: setup SSL Certs
      - bash: |
          #!/bin/bash
          set -e
          sudo nginx -t -c $(Build.SourcesDirectory)/nginx/nginx.conf
        displayName: verify Nginx settings
        workingDirectory: nginx
      - bash: |
          #!/bin/bash
          set -e
          sudo cp nginx.conf /etc/nginx/nginx.conf
          sudo systemctl restart nginx
        displayName: Copy and reload nginx
        workingDirectory: nginx
